/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import logic.*;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class Checkout extends javax.swing.JFrame {


    private Cart cart;
    private double total;
    private static Customer customer;

    //error message
    private static String err = "";
    private ArrayList<String> errors = new ArrayList<>();

    //regex constants;
    private final String ADDRESS_REGEX = "^\\s*$\n";
    public static final Pattern EMAIL_REGEX =
            Pattern.compile("^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$", Pattern.CASE_INSENSITIVE);
    public static final String PHONE_REGEX = "^[0-9]{11}$";


    public Checkout() {

        if (CartCreator.getCart() != null) {
            this.cart = CartCreator.getCart();
        }
        initComponents();
    }

    public static Customer getCustomer() {
        return customer;
    }

    public void setErrMessage() {
        System.out.println(errors);
        for (int i =0 ; i < errors.size(); i ++) {
            if (i < errors.size() - 1) err += errors.get(i)  + ", ";
            else err += errors.get(i) + " ";
        }

        if (errors.size() > 1)
            err += "are incorrect";
        else err += "is incorrect";
    }

    public static String getErrMessage() {
        return err;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {


        paymentButtonGroup = new javax.swing.ButtonGroup();
        navbar = new javax.swing.JPanel();
        brandname = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        checkoutDetails = new javax.swing.JPanel();
        orderDetailsHeading = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        scrollPanel = new javax.swing.JPanel();
        singleItem = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        qty = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        checkoutForm = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cell_phone = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        emailLabel = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        addressLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        paymentOption = new javax.swing.JLabel();
        COD = new javax.swing.JRadioButton();
        online = new javax.swing.JRadioButton();
        proceedBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(254, 254, 254));
        setPreferredSize(new java.awt.Dimension(1300, 670));
        setResizable(false);


        navbar.setBackground(new java.awt.Color(57, 189, 200));
        navbar.setLayout(new java.awt.GridLayout(1, 0));

        brandname.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        brandname.setForeground(new java.awt.Color(254, 254, 254));
        brandname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        brandname.setText("Tahaffuz");
        brandname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                brandnameMouseClicked(evt);
            }
        });
        navbar.add(brandname);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Checkout");
        navbar.add(jLabel1);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cart.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        navbar.add(jLabel3);


        mainPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 1, 1));
        mainPanel.setLayout(new java.awt.GridLayout(1, 0, 10, 10));

        checkoutDetails.setBackground(new java.awt.Color(57, 189, 200));

        orderDetailsHeading.setFont(new java.awt.Font("Ubuntu", 1, 27)); // NOI18N
        orderDetailsHeading.setForeground(new java.awt.Color(254, 254, 254));
        orderDetailsHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        orderDetailsHeading.setText("Order Details");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(802, 900));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(800, 700));

        scrollPanel.setBackground(new java.awt.Color(57, 189, 200));
        scrollPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        scrollPanel.setFocusable(false);
        scrollPanel.setLayout(new javax.swing.BoxLayout(scrollPanel, javax.swing.BoxLayout.Y_AXIS));

        for (Product x : this.cart.getProducts().keySet()) {
            JPanel singleItem = new JPanel();
            singleItem.setBackground(new java.awt.Color(57, 189, 200));
            singleItem.setMaximumSize(new java.awt.Dimension(800, 66));
            singleItem.setPreferredSize(new java.awt.Dimension(700, 70));
            singleItem.setLayout(new java.awt.GridLayout(1, 0));

            JLabel name = new JLabel();
            name.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
            name.setForeground(new java.awt.Color(254, 254, 254));
            name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            name.setText(x.getName());
            singleItem.add(name);

            JLabel price = new JLabel();
            price.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
            price.setForeground(new java.awt.Color(254, 254, 254));
            price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            price.setText(x.getPrice() + " PKR");
            singleItem.add(price);

            JLabel qty = new JLabel();
            qty.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
            qty.setForeground(new java.awt.Color(254, 254, 254));
            qty.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            qty.setText("x" + this.cart.getProducts().get(x));
            singleItem.add(qty);

            scrollPanel.add(singleItem);
        }

        jScrollPane1.setViewportView(scrollPanel);
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(12);

        if (this.cart != null) {
            this.cart.setTotal();
            this.cart.calcTotal();
            this.total = this.cart.getTotal();
        }

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Total Amount: " + this.total + " PKR");
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 20));

        jButton3.setBackground(new java.awt.Color(254, 254, 254));
        jButton3.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jButton3.setText("Return Home");
        jButton3.setAutoscrolls(true);
        jButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton3.setBorderPainted(false);
        jButton3.setFocusable(false);
        jButton3.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                jButton3clicked(actionEvent);
            }
        });

        javax.swing.GroupLayout checkoutDetailsLayout = new javax.swing.GroupLayout(checkoutDetails);
        checkoutDetails.setLayout(checkoutDetailsLayout);
        checkoutDetailsLayout.setHorizontalGroup(
                checkoutDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(orderDetailsHeading, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                        .addGroup(checkoutDetailsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(checkoutDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addGroup(checkoutDetailsLayout.createSequentialGroup()
                                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        checkoutDetailsLayout.setVerticalGroup(
                checkoutDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(checkoutDetailsLayout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(orderDetailsHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                                .addGroup(checkoutDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        mainPanel.add(checkoutDetails);

        checkoutForm.setBackground(new java.awt.Color(57, 189, 200));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 27)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Contact Details");

        jPanel1.setBackground(new java.awt.Color(57, 189, 200));
        jPanel1.setMaximumSize(new java.awt.Dimension(154, 60));
        jPanel1.setLayout(new java.awt.GridLayout());

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cell Phone");
        jLabel5.setMaximumSize(new java.awt.Dimension(49, 35));
        jPanel1.add(jLabel5);

        cell_phone.setToolTipText("Cell phone");
        cell_phone.setFont(new Font("Ubuntu", 0, 17));
        cell_phone.setAutoscrolls(false);
        cell_phone.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0));
        jPanel1.add(cell_phone);

        jPanel2.setBackground(new java.awt.Color(57, 189, 200));
        jPanel2.setMaximumSize(new java.awt.Dimension(154, 60));
        jPanel2.setLayout(new java.awt.GridLayout());

        emailLabel.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(254, 254, 254));
        emailLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emailLabel.setText("Email");
        emailLabel.setMaximumSize(new java.awt.Dimension(49, 35));
        jPanel2.add(emailLabel);

        email.setToolTipText("Email");
        email.setAutoscrolls(false);
        email.setFont(new Font("Ubuntu", 0, 17));
        email.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0));
        jPanel2.add(email);

        jPanel3.setBackground(new java.awt.Color(57, 189, 200));
        jPanel3.setMaximumSize(new java.awt.Dimension(154, 60));
        jPanel3.setLayout(new java.awt.GridLayout());

        addressLabel.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        addressLabel.setForeground(new java.awt.Color(254, 254, 254));
        addressLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addressLabel.setText("Address");
        addressLabel.setMaximumSize(new java.awt.Dimension(49, 35));
        jPanel3.add(addressLabel);

        address.setColumns(0);
        address.setLineWrap(true);
        address.setWrapStyleWord(true);
        address.setRows(5);
        address.setBorder(BorderFactory.createEmptyBorder(5,5,5,5));
        address.setFont(new Font("Ubuntu", 0, 17));
        jScrollPane2.setViewportView(address);

        jScrollPane1.getVerticalScrollBar().setUnitIncrement(12);

        jPanel3.add(jScrollPane2);

        jPanel4.setBackground(new java.awt.Color(57, 189, 200));
        jPanel4.setMaximumSize(new java.awt.Dimension(154, 60));
        jPanel4.setLayout(new java.awt.GridLayout());

        paymentOption.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        paymentOption.setForeground(new java.awt.Color(254, 254, 254));
        paymentOption.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paymentOption.setText("Payment Option");
        paymentOption.setMaximumSize(new java.awt.Dimension(49, 35));
        jPanel4.add(paymentOption);

        COD.setBackground(new java.awt.Color(57, 189, 200));
        COD.setActionCommand("cod");
        paymentButtonGroup.add(COD);
        COD.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        COD.setForeground(new java.awt.Color(254, 254, 254));
        COD.setText("Cash On Delivery");
        COD.setFocusable(false);
        COD.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        COD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CODActionPerformed(evt);
            }
        });
        jPanel4.add(COD);

        online.setBackground(new java.awt.Color(57, 189, 200));
        online.setActionCommand("online");
        paymentButtonGroup.add(online);
        online.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        online.setForeground(new java.awt.Color(254, 254, 254));
        online.setText("Online Payment");
        online.setFocusable(false);
        online.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel4.add(online);


        proceedBtn.setBackground(new java.awt.Color(254, 254, 254));
        proceedBtn.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        proceedBtn.setText("Proceed");
        proceedBtn.setAutoscrolls(true);
        proceedBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        proceedBtn.setBorderPainted(false);
        proceedBtn.setFocusable(false);

        proceedBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                customer = getCustomerDetails();

                if (!verifier(cell_phone.getText(), email.getText(), address.getText(), paymentButtonGroup)) {
                    if (! phoneVerifier(cell_phone.getText())) errors.add("Cell phone");
                    if (! emailVerifier(email.getText())) errors.add("Email");
                    if (! addressVerifier(address.getText())) errors.add("Address");
                    if (paymentButtonGroup.getSelection() == null) errors.add("Payment option");

                    setErrMessage();

                    new error().setVisible(true);

                    errors.clear();
                    err = "";
                }

                else {
                    try {
                        FileOutputStream fs = new FileOutputStream("src/ObjectFiles/customer.dat");
                        ObjectOutputStream os = new ObjectOutputStream(fs);
                        os.writeObject(customer);
                    }catch (Exception e) {
                        e.printStackTrace();
                    }

                    try {
                        FileOutputStream outstream = new FileOutputStream("src/ObjectFiles/cartForPrint.dat", false);
                        ObjectOutputStream os = new ObjectOutputStream(outstream);
                        os.writeObject(cart);
                        os.close();
                    }catch (Exception f) {
                        f.printStackTrace();
                    }

                    new File("src/ObjectFiles/cart.dat").delete();


                    if (customer.getPaymentType() instanceof OnlinePayment) {
                        new OnlinePaymentInfo().setVisible(true);
                    }

                    new SuccessForm().setVisible(true);

                    dispose();
                }

            }
        });

        javax.swing.GroupLayout checkoutFormLayout = new javax.swing.GroupLayout(checkoutForm);
        checkoutForm.setLayout(checkoutFormLayout);
        checkoutFormLayout.setHorizontalGroup(
                checkoutFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(checkoutFormLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(checkoutFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkoutFormLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(proceedBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );
        checkoutFormLayout.setVerticalGroup(
                checkoutFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(checkoutFormLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addComponent(proceedBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        mainPanel.add(checkoutForm);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(navbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(navbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void brandnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brandnameMouseClicked
        this.dispose();
        new Homepage().setVisible(true);
    }//GEN-LAST:event_brandnameMouseClicked

    private void jButton3clicked(java.awt.event.ActionEvent evt) {
        this.dispose();
        new Homepage().setVisible(true);
    }
    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.dispose();
        new CartForm().setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void CODActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CODActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CODActionPerformed

    private Customer getCustomerDetails() {
        this.cellPhone = this.cell_phone.getText();
        this.emailText = this.email.getText();
        this.addressText = this.address.getText();

        Payment payment;
        if (paymentButtonGroup.getSelection() != null && paymentButtonGroup.getSelection().getActionCommand().equals("cod"))  payment = new CashOnDelivery();
        else payment = new OnlinePayment();

        return new Customer(cellPhone, emailText, addressText, payment, cart);
    }

    public boolean phoneVerifier(String text) {
        return text.matches(this.PHONE_REGEX);
    }

    public boolean emailVerifier(String text) {
        Matcher matcher = EMAIL_REGEX.matcher(text);
        return matcher.find();
    }

    public boolean addressVerifier(String text) {
        return !(text.trim().isEmpty());
    }

    public boolean verifier(String cell, String email, String address, ButtonGroup group) {
        return (phoneVerifier(cell) && emailVerifier(email) && addressVerifier(address) && group.getSelection() != null);
    }



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Checkout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private String cellPhone;
    private String emailText;
    private String addressText;
    private javax.swing.JRadioButton COD;
    private javax.swing.JLabel brandname;
    private javax.swing.JPanel checkoutDetails;
    private javax.swing.JPanel checkoutForm;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton proceedBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel paymentOption;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea address;
    private javax.swing.JTextField cell_phone;
    private javax.swing.JTextField email;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel name;
    private javax.swing.JPanel navbar;
    private javax.swing.JRadioButton online;
    private javax.swing.JLabel orderDetailsHeading;
    private javax.swing.ButtonGroup paymentButtonGroup;
    private javax.swing.JLabel price;
    private javax.swing.JLabel qty;
    private javax.swing.JPanel scrollPanel;
    private javax.swing.JPanel singleItem;
    // End of variables declaration//GEN-END:variables
}
