
package project;

import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.*;

import logic.Cart;
import logic.CartCreator;
import logic.Product;

public class SearchResult extends javax.swing.JFrame {

    private ArrayList<Product> products = new ArrayList<>();
    private ArrayList<JPanel> panels = new ArrayList<>();
    private ArrayList<JButton> buttons = new ArrayList<>();
    private ArrayList<Product> searchResult = new ArrayList<>();
    private static Cart cart;

    public SearchResult() {
        cart = CartCreator.getCart();
        initComponents();

    }

    public void generateProducts() {
        this.products.add(new Product("Always sanitary pads", "sanitary", "Always sanitary pads", 300, "/images/always.jpg"));
        this.products.add(new Product("Tampax pocket tampoon", "sanitary", "Tampax pocket tampoon pack", 300, "/images/tampoon.jpg"));
        this.products.add(new Product("Mother care sanitary pads", "sanitary", "Mother care sanitary pads", 180, "/images/mothercare.jpg"));
        this.products.add(new Product("Veet cream 100g", "selfcare", "Veet hair removal cream for women", 400, "/images/veet100.jpeg"));
        this.products.add(new Product("Veet cream 50g", "selfcare", "Veet hair removal cream for women 50g", 150, "/images/veet50.png"));
        this.products.add(new Product("Betadine feminine wash", "sanitary", "Betadine feminie wash", 220, "/images/betadine.jpg"));
        this.products.add(new Product("Butterfly Maxi thick pads", "sanitary", "Butterfly maxi thick pads breathables", 170, "/images/butterfly1.jpeg"));
        this.products.add(new Product("Avent breast pads (20)", "mothercare", "Avent disposable breast pads", 1000, "/images/breastPads.jpg"));
        this.products.add(new Product("Beurer Electric Breast Pump", "mothercare", "Beurer electric breast pump", 13000, "/images/autoPump.jpeg"));
        this.products.add(new Product("Beurer Manual Breast Pump", "mothercare", "Beurer manual breast pump", 4000, "/images/manualPump.jpeg"));
        this.products.add(new Product("Detol soap", "Soaps", "Detol effective soap against germs", 100, "/images/detol.jpg"));
        this.products.add(new Product("Cool and cool wet wipes", "sanitary", "Cool and Cool wet wipes for women", 150, "/images/wetwipes.jpg"));
    }

    public static Cart getCart() {
        return cart;
    }

    public void getSearchResult(String query) {

        query = query.toLowerCase();

        for (Product x : this.products) {
            if (x.getName().toLowerCase().contains(query) || x.getType().toLowerCase().contains(query)) {
                this.searchResult.add(x);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        this.generateProducts();
        if (getFrames()[getFrames().length - 2].getName().equals("homepage")) this.getSearchResult(Homepage.getSearchQuery());
        else this.getSearchResult(Store.getQuery());

        navbar = new javax.swing.JPanel();
        homeBtnPanel = new javax.swing.JPanel();
        homeBtn = new javax.swing.JLabel();
        titlePanel = new javax.swing.JPanel();
        titel = new javax.swing.JLabel();
        lastPanel = new javax.swing.JPanel();
        goShop = new javax.swing.JLabel();
        brandname = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelForScroll = new javax.swing.JPanel();

        picture = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        addToCart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new Dimension(1300, 800));
        setResizable(false);

        navbar.setBackground(new java.awt.Color(57, 189, 200));
        navbar.setMaximumSize(new java.awt.Dimension(1200, 100));
        navbar.setPreferredSize(new java.awt.Dimension(1200, 70));
        navbar.setLayout(new java.awt.GridLayout(1, 0));

        homeBtnPanel.setBackground(new java.awt.Color(57, 189, 200));
        homeBtnPanel.setLayout(new java.awt.BorderLayout());

        homeBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png")));
        homeBtn.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                dispose();
                new Homepage().setVisible(true);
            }
        });
        homeBtnPanel.add(homeBtn, java.awt.BorderLayout.CENTER);

        navbar.add(homeBtnPanel);

        titlePanel.setBackground(new java.awt.Color(57, 189, 200));
        titlePanel.setLayout(new java.awt.BorderLayout());

        titel.setFont(new java.awt.Font("Ubuntu", 1, 30)); // NOI18N
        titel.setForeground(new java.awt.Color(254, 254, 254));
        titel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titel.setText("Search Results");
        titlePanel.add(titel, java.awt.BorderLayout.CENTER);

        navbar.add(titlePanel);

        lastPanel.setBackground(new java.awt.Color(57, 189, 200));
        lastPanel.setLayout(new java.awt.BorderLayout());

        goShop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        goShop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shop.png"))); // NOI18N
        goShop.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                dispose();
                new Store().setVisible(true);
            }
        });
        goShop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lastPanel.add(goShop, java.awt.BorderLayout.CENTER);

        navbar.add(lastPanel);


        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setPreferredSize(new Dimension(950, 606));
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(12);

        panelForScroll.setLayout(new java.awt.GridLayout(0, 3, 30, 30));
        panelForScroll.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245, 246, 247), 2));

        for (int i = 0; i < searchResult.size(); i++) {

            JPanel item = new JPanel();

            JLabel picture = new javax.swing.JLabel();
            JPanel parentBottomPanel = new javax.swing.JPanel();
            JLabel productName = new javax.swing.JLabel();
            JPanel pricePanel = new javax.swing.JPanel();
            JLabel priceLabel = new javax.swing.JLabel();
            JButton addToCart = new javax.swing.JButton();

            item.setBackground(new java.awt.Color(57, 189, 200));
            item.setPreferredSize(new java.awt.Dimension(350, 390));
            item.setLayout(new java.awt.BorderLayout());

            picture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            picture.setIcon(new javax.swing.ImageIcon(getClass().getResource(this.searchResult.get(i).getLink())));
            picture.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 1, 1, 1));
            item.add(picture, java.awt.BorderLayout.CENTER);

            parentBottomPanel.setBackground(new java.awt.Color(57, 189, 200));
            parentBottomPanel.setPreferredSize(new java.awt.Dimension(100, 120));
            parentBottomPanel.setLayout(new java.awt.BorderLayout());

            productName.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
            productName.setForeground(new java.awt.Color(254, 254, 254));
            productName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            productName.setText(this.searchResult.get(i).getName());
            parentBottomPanel.add(productName, java.awt.BorderLayout.CENTER);

            pricePanel.setBackground(new java.awt.Color(57, 189, 200));
            pricePanel.setPreferredSize(new java.awt.Dimension(100, 70));
            pricePanel.setLayout(new java.awt.GridLayout());

            priceLabel.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
            priceLabel.setForeground(new java.awt.Color(254, 254, 254));
            priceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            priceLabel.setText("Price: " + this.searchResult.get(i).getPrice() + " PKR");
            pricePanel.add(priceLabel);

            addToCart.setBackground(new java.awt.Color(57, 189, 200));
            addToCart.setForeground(new java.awt.Color(57, 189, 200));
            addToCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addToCart.png"))); // NOI18N
            addToCart.setBorderPainted(false);
            addToCart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            addToCart.setFocusPainted(false);
            addToCart.setActionCommand(this.searchResult.get(i).getName());
            addToCart.setPreferredSize(new java.awt.Dimension(50, 10));
            pricePanel.add(addToCart);

            parentBottomPanel.add(pricePanel, java.awt.BorderLayout.PAGE_END);

            item.add(parentBottomPanel, java.awt.BorderLayout.PAGE_END);

            panelForScroll.add(item);
            this.panels.add(item);

        }

        jScrollPane1.setViewportView(panelForScroll);
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 30, 20));


        if (this.searchResult.size() == 0) {
            JLabel x = new JLabel("No search results found :(");
            x.setHorizontalAlignment(SwingConstants.CENTER);
            x.setFont(new Font("Ubuntu", 0, 40));
            panelForScroll.setLayout(new GridLayout(0, 1));
            panelForScroll.add(x);
        }

        if (this.searchResult.size() > 0) {
            for (int i = 0; i < this.searchResult.size(); i++) {
                JPanel itemPanel = (JPanel) panelForScroll.getComponent(i);
                JPanel bottomPanel = (JPanel) itemPanel.getComponent(1);
                JPanel pricePanel = (JPanel) bottomPanel.getComponent(1);
                JButton addToCart = (JButton) pricePanel.getComponent(1);

                addToCart.addActionListener(new java.awt.event.ActionListener() {
                    @Override
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        Product x = addToCartActionPerformed(evt);
                        cart.addToCart(x);
                        try {
                            FileOutputStream outstream = new FileOutputStream("src/ObjectFiles/cart.dat", false);
                            ObjectOutputStream os = new ObjectOutputStream(outstream);
                            os.writeObject(cart);

                            os.close();
                        }catch (Exception f) {
                            f.printStackTrace();
                        }
                    }
                });
            }
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(navbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1047, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(navbar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void brandnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brandnameMouseClicked
        this.dispose();
        new Homepage().setVisible(true);
    }//GEN-LAST:event_brandnameMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.dispose();
        new CartForm().setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private Product addToCartActionPerformed(java.awt.event.ActionEvent evt) {
        String output = evt.getActionCommand();


        for (int i = 0; i < products.size(); i++) {
            if (products.get(i).getName().equals(output)) {
                return products.get(i);
            }
        }

        return null;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Store().setVisible(true);
            }
        });
    }


    private javax.swing.JButton addToCart;
    private javax.swing.JLabel brandname;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel navbar;
    private javax.swing.JPanel panelForScroll;
    private javax.swing.JLabel picture;
    private javax.swing.JLabel price;
    private javax.swing.JLabel title;
    private javax.swing.JLabel goShop;
    private javax.swing.JLabel homeBtn;
    private javax.swing.JPanel homeBtnPanel;
    private javax.swing.JPanel item;
    private javax.swing.JPanel lastPanel;
    private javax.swing.JLabel titel;
    private javax.swing.JPanel titlePanel;

}
