	/*
     * To change this license header, choose License Headers in Project Properties.
     * To change this template file, choose Tools | Templates
     * and open the template in the editor.
     */
    package project;

    import java.awt.*;
    import java.io.*;
    import java.util.ArrayList;
    import java.util.HashMap;
    import java.util.Map;
    import javax.swing.*;

    import logic.Cart;
    import logic.CartCreator;
    import logic.Product;

    public class Store extends javax.swing.JFrame {


        private ArrayList<Product> products = new ArrayList<>();
        private ArrayList<JPanel> panels = new ArrayList<>();
        private ArrayList<JButton> buttons = new ArrayList<>();
        private Map<Product, Integer> addedToCart = new HashMap<Product, Integer>();
        private Cart cart;
        private static String query;


        public Store() {

            this.cart = CartCreator.getCart();
            initComponents();
        }

        public void generateProducts() {
            this.products.add(new Product("Always sanitary pads", "sanitary", "Always sanitary pads", 300, "/images/always.jpg"));
            this.products.add(new Product("Tampax pocket tampoon", "sanitary", "Tampax pocket tampoon pack", 300, "/images/tampoon.jpg"));
            this.products.add(new Product("Mother care sanitary pads", "sanitary", "Mother care sanitary pads", 180, "/images/mothercare.jpg"));
            this.products.add(new Product("Veet cream 100g", "self care", "Veet hair removal cream for women", 400, "/images/veet100.jpeg"));
            this.products.add(new Product("Veet cream 50g", "self care", "Veet hair removal cream for women 50g", 150, "/images/veet50.png"));
            this.products.add(new Product("Betadine feminine wash", "sanitary", "Betadine feminie wash", 220, "/images/betadine.jpg"));
            this.products.add(new Product("Butterfly Maxi thick pads", "sanitary", "Butterfly maxi thick pads breathables", 170, "/images/butterfly1.jpeg"));
            this.products.add(new Product("Avent breast pads (20)", "mother care", "Avent disposable breast pads", 1000, "/images/breastPads.jpg"));
            this.products.add(new Product("Beurer Electric Breast Pump", "mother care", "Beurer electric breast pump", 13000, "/images/autoPump.jpeg"));
            this.products.add(new Product("Beurer Manual Breast Pump", "mother care", "Beurer manual breast pump", 4000, "/images/manualPump.jpeg"));
            this.products.add(new Product("Detol soap", "Soaps", "Detol effective soap against germs", 100, "/images/detol.jpg"));
            this.products.add(new Product("Cool and cool wet wipes", "sanitary", "Cool and Cool wet wipes for women", 150, "/images/wetwipes.jpg"));

        }

        public static String getQuery() {
            return query;
        }

        public Cart getCart() {
            return cart;
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

            this.generateProducts();

            navbar = new javax.swing.JPanel();
            brandname = new javax.swing.JLabel();
            jTextField1 = new javax.swing.JTextField();
            jLabel3 = new javax.swing.JLabel();
            jScrollPane1 = new javax.swing.JScrollPane();
            panelForScroll = new javax.swing.JPanel();

            picture = new javax.swing.JLabel();
            title = new javax.swing.JLabel();
            price = new javax.swing.JLabel();
            addToCart = new javax.swing.JButton();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setPreferredSize(new Dimension(1300, 800));
            setResizable(false);
            setName("store");


            navbar.setBackground(new java.awt.Color(57, 189, 200));

            brandname.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
            brandname.setForeground(new java.awt.Color(254, 254, 254));
            brandname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            brandname.setText("Tahaffuz");
            brandname.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    brandnameMouseClicked(evt);
                }
            });

            jTextField1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
            jTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            jTextField1.setToolTipText("Search for products");
            jTextField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
            jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
            jTextField1.setMargin(new java.awt.Insets(2, 2, 2, 2));
            jTextField1.setMinimumSize(new java.awt.Dimension(40, 35));
            jTextField1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jTextField1ActionPerformed(evt);
                }
            });

            jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cart.png"))); // NOI18N
            jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jLabel3MouseClicked(evt);
                }
            });

            javax.swing.GroupLayout navbarLayout = new javax.swing.GroupLayout(navbar);
            navbar.setLayout(navbarLayout);
            navbarLayout.setHorizontalGroup(
                    navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(navbarLayout.createSequentialGroup()
                                    .addGap(52, 52, 52)
                                    .addComponent(brandname)
                                    .addGap(185, 185, 185)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                                    .addComponent(jLabel3)
                                    .addGap(56, 56, 56))
            );
            navbarLayout.setVerticalGroup(
                    navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .addComponent(brandname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(navbarLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addContainerGap())
            );

            jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
            jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
            jScrollPane1.setPreferredSize(new Dimension(950, 606));
            jScrollPane1.getVerticalScrollBar().setUnitIncrement(12);

            panelForScroll.setLayout(new java.awt.GridLayout(0,3,30,30));
            panelForScroll.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245, 246, 247), 2));

            for (int i = 0; i < products.size(); i++) {

                JPanel item = new JPanel();

                item.setToolTipText(products.get(i).getDescription());

                JLabel picture = new javax.swing.JLabel();
                JPanel parentBottomPanel = new javax.swing.JPanel();
                JLabel productName = new javax.swing.JLabel();
                JPanel pricePanel = new javax.swing.JPanel();
                JLabel priceLabel = new javax.swing.JLabel();
                JButton addToCart = new javax.swing.JButton();

                item.setBackground(new java.awt.Color(57, 189, 200));
                item.setPreferredSize(new java.awt.Dimension(350, 390));
                item.setLayout(new java.awt.BorderLayout());

                picture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                picture.setIcon(new javax.swing.ImageIcon(getClass().getResource(this.products.get(i).getLink())));
                picture.setBorder(javax.swing.BorderFactory.createEmptyBorder(20,1,1,1));
                item.add(picture, java.awt.BorderLayout.CENTER);

                parentBottomPanel.setBackground(new java.awt.Color(57, 189, 200));
                parentBottomPanel.setPreferredSize(new java.awt.Dimension(100, 120));
                parentBottomPanel.setLayout(new java.awt.BorderLayout());

                productName.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
                productName.setForeground(new java.awt.Color(254, 254, 254));
                productName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                productName.setText(this.products.get(i).getName());
                parentBottomPanel.add(productName, java.awt.BorderLayout.CENTER);

                pricePanel.setBackground(new java.awt.Color(57, 189, 200));
                pricePanel.setPreferredSize(new java.awt.Dimension(100, 70));
                pricePanel.setLayout(new java.awt.GridLayout());

                priceLabel.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
                priceLabel.setForeground(new java.awt.Color(254, 254, 254));
                priceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                priceLabel.setText("Price: " + this.products.get(i).getPrice() + " PKR");
                pricePanel.add(priceLabel);

                addToCart.setBackground(new java.awt.Color(57, 189, 200));
                addToCart.setForeground(new java.awt.Color(57, 189, 200));
                addToCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addToCart.png"))); // NOI18N
                addToCart.setBorderPainted(false);
                addToCart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                addToCart.setFocusPainted(false);
                addToCart.setActionCommand(this.products.get(i).getName());
                addToCart.setPreferredSize(new java.awt.Dimension(50, 10));
                pricePanel.add(addToCart);

                parentBottomPanel.add(pricePanel, java.awt.BorderLayout.PAGE_END);

                item.add(parentBottomPanel, java.awt.BorderLayout.PAGE_END);

                panelForScroll.add(item);
                this.panels.add(item);

            }

            jScrollPane1.setViewportView(panelForScroll);
            jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(20,20,30,20));


            for (int i = 0; i < this.products.size(); i ++) {
                JPanel itemPanel = (JPanel) panelForScroll.getComponent(i);
                JPanel bottomPanel = (JPanel) itemPanel.getComponent(1);
                JPanel pricePanel = (JPanel) bottomPanel.getComponent(1);
                JButton addToCart = (JButton) pricePanel.getComponent(1);

                addToCart.addActionListener(new java.awt.event.ActionListener() {
                    @Override
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        Product x = addToCartActionPerformed(evt);
                        cart.addToCart(x);
                        try {
                            FileOutputStream outstream = new FileOutputStream("src/ObjectFiles/cart.dat", false);
                            ObjectOutputStream os = new ObjectOutputStream(outstream);
                            os.writeObject(cart);

                            os.close();
                        }catch (Exception f) {
                            f.printStackTrace();
                        }

                        System.out.println(cart);
                    }
                });
            }

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(navbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1047, Short.MAX_VALUE)
                                    .addContainerGap())
            );
            layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                    .addComponent(navbar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE))
            );

            pack();
            setLocationRelativeTo(null);
        }// </editor-fold>

        private void brandnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brandnameMouseClicked
            this.dispose();
            new Homepage().setVisible(true);
        }//GEN-LAST:event_brandnameMouseClicked

        private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
            query = jTextField1.getText();
            this.dispose();
            new SearchResult().setVisible(true);
        }//GEN-LAST:event_jTextField1ActionPerformed

        private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
            this.dispose();
            new CartForm().setVisible(true);
        }//GEN-LAST:event_jLabel3MouseClicked

        private Product addToCartActionPerformed(java.awt.event.ActionEvent evt) {
            String output = evt.getActionCommand();


            for (int i = 0; i < products.size(); i++) {
                if (products.get(i).getName().equals(output)) {
                    return products.get(i);
                }
            }

            return null;
        }

        private javax.swing.JButton addToCart;
        private javax.swing.JLabel brandname;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTextField jTextField1;
        private javax.swing.JPanel navbar;
        private javax.swing.JPanel panelForScroll;
        private javax.swing.JLabel picture;
        private javax.swing.JLabel price;
        private javax.swing.JLabel title;

    }
