/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import logic.Cart;
import logic.CartCreator;
import logic.Customer;

import javax.swing.*;
import java.awt.*;


public class SuccessForm extends javax.swing.JFrame {

    private Customer customer;
    private Cart cart;
    /**
     * Creates new form SuccessForm
     */
    public SuccessForm() {
        this.customer = Checkout.getCustomer();
        if (CartCreator.getCart() != null) {
            cart = CartCreator.getCart();
        }

        customer = Checkout.getCustomer();
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cellLabel = new javax.swing.JLabel();
        cellPhone = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        paymentTypLabel = new javax.swing.JLabel();
        paymentTYpe = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        totalAmount = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(798, 647));
        setTitle("Order successfully placed");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(57, 189, 200));
        jPanel1.setMaximumSize(new java.awt.Dimension(1000, 200));
        jPanel1.setPreferredSize(new java.awt.Dimension(1064, 90));
        jPanel1.setLayout(new java.awt.GridLayout());


        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/success.png"))); // NOI18N
        jLabel3.setText("Order successfully placed!");
        jPanel1.add(jLabel3);

        jPanel2.setLayout(new java.awt.GridLayout(5, 0));

        cellLabel.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        cellLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cellLabel.setText("Cell Phone");
        jPanel2.add(cellLabel);

        cellPhone.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        cellPhone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cellPhone.setText(customer.getPhone());
        jPanel2.add(cellPhone);

        emailLabel.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        emailLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emailLabel.setText("Email");
        jPanel2.add(emailLabel);

        email.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        email.setText(customer.getEmail());
        jPanel2.add(email);

        addressLabel.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        addressLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addressLabel.setText("Address");
        jPanel2.add(addressLabel);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(10);
        jTextArea1.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(2);
        jTextArea1.setText(customer.getAddress());
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jTextArea1.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1);

        paymentTypLabel.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        paymentTypLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paymentTypLabel.setText("Payment type");
        jPanel2.add(paymentTypLabel);

        paymentTYpe.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        paymentTYpe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paymentTYpe.setText(customer.getPaymentType().toString());
        jPanel2.add(paymentTYpe);

        totalLabel.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        totalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalLabel.setText("Total amount");
        totalLabel.setBorder(BorderFactory.createLineBorder(new Color(57,189,200), 2));
        jPanel2.add(totalLabel);

        totalAmount.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        totalAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalAmount.setText(this.cart.getTotal() + " PKR");
        totalAmount.setBorder(BorderFactory.createLineBorder(new Color(57,189,200),2));
        jPanel2.add(totalAmount);

        jPanel3.setMaximumSize(new java.awt.Dimension(1000, 50));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Summary");
        jLabel1.setMaximumSize(new java.awt.Dimension(798, 50));
        jLabel1.setPreferredSize(new java.awt.Dimension(798, 50));
        jLabel1.setRequestFocusEnabled(false);
        jPanel3.add(jLabel1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
        );



        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuccessForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuccessForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuccessForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuccessForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuccessForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel cellLabel;
    private javax.swing.JLabel cellPhone;
    private javax.swing.JLabel email;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel paymentTYpe;
    private javax.swing.JLabel paymentTypLabel;
    private javax.swing.JLabel totalAmount;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
